from albumentations.core.transforms_interface import BasicTransform
import numpy as np

# Generated by Claude AI

class CellAwareCrop(BasicTransform):
    def __init__(self, crop_size=144, min_cell_fraction=0.05,
                 max_attempts=20, always_apply=False, p=1.0):
        super().__init__(p=p)
        self.crop_size = crop_size
        self.min_cell_fraction = min_cell_fraction
        self.max_attempts = max_attempts

    @property
    def targets(self):
        return {"image": self.apply, "mask": self.apply}

    def apply(self, img, y=0, x=0, **params):
        cs = self.crop_size
        return img[y:y+cs, x:x+cs]

    def get_params_dependent_on_data(self, params, data):
        mask  = data['mask']
        h, w  = mask.shape[:2]
        cs    = self.crop_size
        y = np.random.randint(0, max(1, h - cs))
        x = np.random.randint(0, max(1, h - cs))

        for _ in range(self.max_attempts):
            _y = np.random.randint(0, max(1, h - cs))
            _x = np.random.randint(0, max(1, w - cs))
            if mask[_y:_y+cs, _x:_x+cs].mean() >= self.min_cell_fraction:
                y, x = _y, _x
                return {'y': y, 'x': x}
        
        # fallback to random
        y = np.random.randint(0, max(1, h - cs))
        x = np.random.randint(0, max(1, h - cs))
        return {'y': y, 'x': x}


    def get_transform_init_args_names(self):
        return ('crop_size', 'min_cell_fraction', 'max_attempts')